# Generated by Django 6.0.1 on 2026-02-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_product_productcolor_product_productstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.CharField(max_length=25)),
                ('carPrice', models.IntegerField()),
                ('carStock', models.PositiveBigIntegerField()),
                ('carColor', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
