# Generated by Django 6.0.1 on 2026-02-08 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_category_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructorName', models.CharField(max_length=100)),
                ('instructorEmail', models.EmailField(max_length=254, unique=True)),
                ('instructorPhone', models.CharField(max_length=15)),
                ('instructorStatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'instructor',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchName', models.CharField(max_length=100)),
                ('batchStartDate', models.DateField()),
                ('batchEndDate', models.DateField()),
                ('batchStatus', models.BooleanField(default=True)),
                ('instructorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.instructor')),
            ],
            options={
                'db_table': 'batch',
            },
        ),
    ]
