# Generated by Django 6.0.1 on 2026-02-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_instructor_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='instructorPhone',
            field=models.CharField(max_length=10),
        ),
    ]
